FROM arm32v7/openjdk:11-jdk-slim

# Enable us to build ARM images in an i386 environment
COPY qemu-arm-static /usr/bin/qemu-arm-static

RUN apt-get update -y
RUN apt-get upgrade -y
RUN apt-get install -y wget

RUN mkdir ~/minecraft
WORKDIR /minecraft
RUN wget -O paper-1.15.2-build372.jar https://papermc.io/api/v1/paper/1.15.2/372/download

#VOLUME ["/data"]
RUN mkdir /data

RUN echo eula=true > /data/eula.txt

ENV JVM_XX_OPTS="-XX:+UseG1GC" MEMORY="1G" \
  TYPE=SPIGOT VERSION=LATEST FORGEVERSION=RECOMMENDED SPONGEBRANCH=STABLE SPONGEVERSION= FABRICVERSION=LATEST LEVEL=world \
  PVP=true DIFFICULTY=easy ENABLE_RCON=true RCON_PORT=25575 RCON_PASSWORD=minecraft \
  LEVEL_TYPE=DEFAULT SERVER_PORT=25565 ONLINE_MODE=TRUE SERVER_NAME="Ramsay's Spigot Server" \
  REPLACE_ENV_VARIABLES="FALSE" ENV_VARIABLE_PREFIX="CFG_" \
  ENABLE_AUTOPAUSE=false AUTOPAUSE_TIMEOUT_EST=3600 AUTOPAUSE_TIMEOUT_KN=120 AUTOPAUSE_TIMEOUT_INIT=600 AUTOPAUSE_PERIOD=10

COPY rcon-cli_1.4.8_linux_armv7/rcon-cli /

WORKDIR /data

EXPOSE 25565 25575

ENTRYPOINT [ "java",  "-Xms256M", "-Xmx2048M", "-jar", "/minecraft/paper-1.15.2-build372.jar", "nogui"]
