FROM arm32v7/openjdk:11-jdk-slim

# Enable us to build ARM images in an i386 environment
COPY qemu-arm-static /usr/bin/qemu-arm-static

RUN apt-get update -y
RUN apt-get upgrade -y
RUN apt-get install -y wget

RUN mkdir ~/minecraft
WORKDIR /minecraft
RUN wget -O paper-1.16.1-latest.jar https://papermc.io/api/v1/paper/1.16.1/latest/download

#VOLUME ["/data"]
RUN mkdir /data

RUN echo eula=true > /data/eula.txt

COPY rcon-cli_1.4.8_linux_armv7/rcon-cli /

WORKDIR /data

EXPOSE 25565 25575

ENTRYPOINT [ "java",  "-Xms256M", "-Xmx2048M", "-XX:+UseG1GC", "-jar", "/minecraft/paper-1.16.1-latest.jar", "nogui"]
