apiVersion: v1
kind: Service
metadata:
  name: minecraft-service
spec:
  type: LoadBalancer
  selector:
    app: minecraft
  ports:
    - protocol: TCP
      port: 25565 # the port to expose to the world
      targetPort: 25565 # the actual port the container is listening on
