apiVersion: apps/v1
kind: Deployment
metadata:
  name: minecraft
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minecraft
      version: v1
  template:
    metadata:
      labels:
        app: minecraft
        version: v1
    spec:
      nodeName: k8s-node-6 #always schedule to node 6
      containers:
        - name: minecraft
          image: rdomloge/minecraft-spigot:1.16.2
          command: ["java"]
          args: ["-Xms3G", "-Xmx3G", "-XX:+UseG1GC", "-XX:+ParallelRefProcEnabled", "-XX:MaxGCPauseMillis=200", "-XX:+UnlockExperimentalVMOptions", "-XX:+DisableExplicitGC", "-XX:+AlwaysPreTouch", "-XX:G1NewSizePercent=30", "-XX:G1MaxNewSizePercent=40", "-XX:G1HeapRegionSize=8M", "-XX:G1ReservePercent=20", "-XX:G1HeapWastePercent=5", "-XX:G1MixedGCCountTarget=4", "-XX:InitiatingHeapOccupancyPercent=15", "-XX:G1MixedGCLiveThresholdPercent=90", "-XX:G1RSetUpdatingPauseTimePercent=5", "-XX:SurvivorRatio=32", "-XX:+PerfDisableSharedMem", "-XX:MaxTenuringThreshold=1", "-Dusing.aikars.flags=https://mcflags.emc.gs", "-Daikars.new.flags=true", "-jar", "-Dcom.sun.management.jmxremote", "-Dcom.sun.management.jmxremote.port=9990", "-Dcom.sun.management.jmxremote.authenticate=false", "-Dcom.sun.management.jmxremote.ssl=false", "../spigot-1.16.2.jar", "nogui"]
          volumeMounts: 
            - name: minecraft-data
              mountPath: /data
          env:
          - name: JAVA_TOOL_OPTIONS 
            value: "-agentlib:jdwp=transport=dt_socket,address=8000,server=y,suspend=n,address=*:8000"
          imagePullPolicy: Always
          ports:
            - containerPort: 25565
            - containerPort: 25575
            - containerPort: 8000
            - containerPort: 9990
          resources:
            limits:
              memory: "4Gi"
              cpu: "4"
            requests:
              memory: "4Gi"
              cpu: 3000m
          livenessProbe:
            exec:
              command:
                - ../rcon-cli
                - --port 
                - "25575"
                - --password 
                - minecraft
                - help
            initialDelaySeconds: 120
            periodSeconds: 60
      volumes:
      - name: minecraft-data
        persistentVolumeClaim:
          claimName: minecraft-data
