apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: minecraft
  namespace: mc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minecraft
      version: v1
  serviceName: minecraft
  template:
    metadata:
      labels:
        app: minecraft
        version: v1
    spec:
      #nodeName: k8s-node-6 #always schedule to node 6
      containers:
        - name: minecraft
          image: itzg/minecraft-server:latest
          livenessProbe:
            exec:
              command:
              - rcon-cli
              - list
            periodSeconds: 60
          startupProbe:
            exec:
              command:
              - grep
              - 'RCON running on'
              - logs/latest.log
            initialDelaySeconds: 120
            periodSeconds: 30
            failureThreshold: 30
          volumeMounts:
            - name: minecraft-data
              mountPath: /data
          env:
          - name: EULA
            value: "TRUE"
          - name: USE_AIKAR_FLAGS
            value: "true"
          - name: MEMORY
            value: "3500M"
          - name: TYPE
            value: "FORGE"
          - name: PLAYER_IDLE_TIMEOUT
            value: "0"
          - name: VERSION
            value: "1.18.1"
          imagePullPolicy: Always
          ports:
            - containerPort: 25565
            - containerPort: 25575
            - containerPort: 8000
            - containerPort: 9990
          resources:
            limits:
              memory: "4Gi"
              #cpu: "4" commented out so that there is no limit
            requests:
              memory: "4Gi"
              cpu: 2750m
      volumes:
      - name: minecraft-data
        persistentVolumeClaim:
          claimName: minecraft-data
