apiVersion: apps/v1
kind: Deployment
metadata:
  name: minecraft
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minecraft
      version: v1
  template:
    metadata:
      labels:
        app: minecraft
        version: v1
    spec:
      nodeName: k8s-node-4 #always schedule to node 4
      containers:
        - name: minecraft
          image: rdomloge/minecraft-spigot
          volumeMounts: 
            - name: minecraft-data
              mountPath: /data
          env:
          - name: EULA
            value: "true"
          - name: MEMORY
            value: "2G"
          - name: TYPE
            value: "SPIGOT"
          imagePullPolicy: Always
          ports:
            - containerPort: 25565
            - containerPort: 25575
          resources:
            limits:
              cpu: "4"
            requests:
              cpu: 3000m
      volumes:
      - name: minecraft-data
        persistentVolumeClaim:
          claimName: minecraft-data
