apiVersion: v1
kind: Service
metadata:
  name: minecraft-service
spec:
  type: LoadBalancer
  selector:
    app: minecraft
  ports:
    - protocol: TCP
      port: 25565
      nodePort: 32565
      targetPort: 25565
