apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: minecraft
  namespace: mc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minecraft
      version: v1
  serviceName: minecraft
  template:
    metadata:
      labels:
        app: minecraft
        version: v1
    spec:
      #nodeName: k8s-node-6 #always schedule to node 6
      containers:
        - name: minecraft
          image: itzg/minecraft-server:java8-multiarch
          livenessProbe:
            exec:
              command:
              - rcon-cli
              - list
            periodSeconds: 60
          startupProbe:
            exec:
              command:
              - grep
              - 'For help, type "help"'
              - logs/latest.log
            initialDelaySeconds: 300
            periodSeconds: 10
            failureThreshold: 30
          volumeMounts:
            - name: minecraft-data
              mountPath: /data
          env:
          - name: EULA
            value: "TRUE"
          - name: USE_AIKAR_FLAGS
            value: "true"
          - name: MEMORY
            value: "4500M"
          - name: TYPE
            value: "FORGE"
          - name: PLAYER_IDLE_TIMEOUT
            value: "0"
          - name: VERSION
            value: "1.12.2"
          - name: FORGEVERSION
            value: "14.23.5.2860"
          - name: DIFFICULTY
            value: "hard"
          - name: JVM_DD_OPTS
            value: "fml.readTimeout=60"
          - name: JVM_XX_OTPS
            value: "-XX:MaxGCPauseMillis=50"
          imagePullPolicy: Always
          ports:
            - containerPort: 25565
            - containerPort: 25575
            - containerPort: 8000
            - containerPort: 9990
          resources:
            limits:
              memory: "6500Mi"
              #cpu: "4" commented out so that there is no limit
            requests:
              memory: "6500Mi"
              cpu: 2750m
      volumes:
      - name: minecraft-data
        persistentVolumeClaim:
          claimName: minecraft-data
