apiVersion: v1
kind: Service
metadata:
  name: minecraft-service
  namespace: mc
spec:
  type: LoadBalancer
  externalIPs:
    - 10.0.0.12
  loadBalancerIP: 10.0.0.12
  selector:
    app: minecraft
  ports:
    - name: mc
      protocol: TCP
      port: 25565 # the port to expose to the world
      targetPort: 25565 # the actual port the container is listening on
