apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: meg-minecraft-paper
  namespace: meg
spec:
  replicas: 1
  selector:
    matchLabels:
      app: meg-minecraft
      version: v1
  serviceName: "meg-minecraft-service"
  template:
    metadata:
      labels:
        app: meg-minecraft
        version: v1
    spec:
      #nodeName: k8s-node-6 #always schedule to node 6
      containers:
        - name: meg-minecraft
          image: itzg/minecraft-server:java17
          livenessProbe:
            exec:
              command:
              - rcon-cli
              - list
            periodSeconds: 60
            failureThreshold: 3
          startupProbe:
            exec:
              command:
              - grep
              - 'For help, type "help"'
              - logs/latest.log
            initialDelaySeconds: 840
            periodSeconds: 20
            failureThreshold: 30
          volumeMounts:
            - name: meg-minecraft-data
              mountPath: /data
          env:
          - name: EULA
            value: "TRUE"
          - name: USE_AIKAR_FLAGS
            value: "true"
          - name: MEMORY
            value: "3G"
          - name: TYPE
            value: "FORGE"
          - name: VERSION
            value: "1.18.2"
          - name: FORGEVERSION
            value: "40.1.68"
          - name: PLAYER_IDLE_TIMEOUT
            value: "0"
          imagePullPolicy: Always
          ports:
            - containerPort: 25565
            - containerPort: 25575
            - containerPort: 8000
            - containerPort: 9990
          resources:
            limits:
              memory: "4Gi"
            requests:
              memory: "4Gi"
              cpu: 1000m
      volumes:
      - name: meg-minecraft-data
        persistentVolumeClaim:
          claimName: meg-minecraft-data
