apiVersion: v1
kind: Service
metadata:
  name: meg-minecraft-service
spec:
  type: LoadBalancer
  externalIPs:
    - 10.0.0.12
  loadBalancerIP: 10.0.0.12
  selector:
    app: meg-minecraft
  ports:
    - protocol: TCP
      port: 25566 # the port to expose to the world
      targetPort: 25565 # the actual port the container is listening on
