apiVersion: v1
kind: Service
metadata:
  name: meg-minecraft-service
spec:
  type: LoadBalancer
  selector:
    app: meg-minecraft
  ports:
    - protocol: TCP
      port: 25565
      nodePort: 32567
      targetPort: 25565
