apiVersion: v1
kind: Service
metadata:
  name: kaiden-minecraft-service
spec:
  type: LoadBalancer
  loadBalancerIP: 10.0.0.12
  selector:
    app: kaiden-minecraft
  ports:
    - protocol: TCP
      port: 25568 # the port to expose to the world
      targetPort: 25565 # the actual port the container is listening on
