kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: skyblock-data
  namespace: skyblock
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 10Gi
