apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: fin-minecraft-paper
  namespace: fin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fin-minecraft-paper
      version: v1
  serviceName: fin-minecraft-service
  template:
    metadata:
      labels:
        app: fin-minecraft-paper
        version: v1
    spec:
      #nodeName: k8s-node-6 #always schedule to node 6
      containers:
        - name: fin-minecraft-paper
          image: itzg/minecraft-server:multiarch-latest
          livenessProbe:
            exec:
              command:
              - rcon-cli
              - list
            periodSeconds: 60
          startupProbe:
            exec:
              command:
              - grep
              - 'Timings Reset'
              - logs/latest.log
            initialDelaySeconds: 30
            periodSeconds: 5
            failureThreshold: 30
          volumeMounts:
            - name: fin-minecraft-data
              mountPath: /data
          env:
          - name: EULA
            value: "TRUE"
          - name: USE_AIKAR_FLAGS
            value: "true"
          - name: MEMORY
            value: "3G"
          - name: TYPE
            value: "PAPER"
          - name: PLAYER_IDLE_TIMEOUT
            value: "0"
          imagePullPolicy: Always
          ports:
            - containerPort: 25565
            - containerPort: 25575
            - containerPort: 8000
            - containerPort: 9990
          resources:
            limits:
              memory: "4Gi"
              cpu: "4"
            requests:
              memory: "4Gi"
              cpu: 2750m
      volumes:
      - name: fin-minecraft-data
        persistentVolumeClaim:
          claimName: fin-minecraft-data
