apiVersion: v1
kind: Service
metadata:
  name: fin-minecraft-service
spec:
  type: LoadBalancer
  selector:
    app: fin-minecraft
  ports:
    - protocol: TCP
      port: 25565
      nodePort: 32566
      targetPort: 25565
