apiVersion: v1
kind: Service
metadata:
  name: fin-minecraft-service
spec:
  type: LoadBalancer
  selector:
    app: fin-minecraft
  ports:
    - protocol: TCP
      port: 25567 # the port to expose to the world
      targetPort: 25565 # the actual port the container is listening on
