apiVersion: apps/v1
kind: Deployment
metadata:
  name: fin-minecraft
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fin-minecraft
      version: v1
  template:
    metadata:
      labels:
        app: fin-minecraft
        version: v1
    spec:
      #nodeName: k8s-node-4 #always schedule to node 4
      containers:
        - name: fin-minecraft
          image: rdomloge/minecraft-spigot
          volumeMounts: 
            - name: fin-minecraft-data
              mountPath: /data
          env:
          - name: EULA
            value: "true"
          - name: MEMORY
            value: "2G"
          - name: TYPE
            value: "SPIGOT"
          imagePullPolicy: Always
          ports:
            - containerPort: 25565
            - containerPort: 25575
          resources:
            limits:
              cpu: "2"
            requests:
              cpu: 2000m
          livenessProbe:
            exec:
              command:
              - ../rcon-cli 
              - help
            initialDelaySeconds: 300
            periodSeconds: 60
      volumes:
      - name: fin-minecraft-data
        persistentVolumeClaim:
          claimName: fin-minecraft-data
