apiVersion: v1
kind: PersistentVolume
metadata:
  name: fin-minecraft-nfs
spec:
  capacity:
    storage: 10Gi
  storageClassName: standard
  accessModes:
  - ReadWriteOnce
  nfs:
    server: 10.0.0.60
    path: "/volume1/fin-minecraft"
